### ISSUE TITLE
Enable Contiki building

### ISSUE THREAD

**Issue by asl** [access-softek/msp430-clang#50]
http://www.contiki-os.org/

**Comment by chbessonova** [comment]
There are two issues with Contiki build:
1. Contiki code and build system are compatible with old mspgcc toolchain. 
It required some efforts and source code changes to make it compatible with new msp430-gcc toolchain as well as clang (e.g. align defines, headers, build options, etc.)
2. The most recent version of Contiki OS (version 3.1) supports only one MSP430 device - MSP430F2617 (Zolertia z1) - which has CPUXv2 on the board. So, we can build it only in "compatibility" mode under MSP430 ISA. 

I was able to almost resolve these issues (except #59) by [52670f5](https://github.com/contiki-os/contiki/commit/52670f5631354407ac8e802dd1dbb7acf9b6646b) and [2924891](https://github.com/contiki-os/contiki/commit/2924891f577019da5c78e01feb394e0ab1a1a903), but looks like it's not a valid case to compile code for 430 ISA and then try to link it using original linker script (which is done for MSP430Xv2 device). 

As a reference, I tried to build Contiki under MSP430F2617 by msp430-gcc toolchain (new gcc), it compiled successfully, but failed with the link error:
```
msp430-elf/bin/ld: hello-world.z1 section `.text' will not fit in region `ROM'
msp430-elf/bin/ld: section __interrupt_vector_17 loaded at [000000000000ffe0,000000000000ffe1] overlaps section .text loaded at [00000000000038ee,00000000000117d5]
msp430-elf/bin/ld: region `ROM' overflowed by 6168 bytes
```
It required some more code changes to get it working.

So, I gave up with Contiki 3.1 and z1 build, and back to Contiki 2.6 that supports some more msp430 targets.

To build `hello_world` example clang and gnu ar/ld for **esb target (msp430f149)**:
```
git clone https://github.com/contiki-os/contiki
/* Checkout the latest revision where esb is supported */
git checkout 2133c1d7777225bc857a6bd0c9db6eeff58f63e8

/* For fixes to build with clang */
git apply https://github.com/contiki-os/contiki/commit/4dd63d06f32aa994f9f58bac56651709522e3287
git apply https://github.com/contiki-os/contiki/commit/88a5b3bfcc764e5dc5dd486af9e79f6c53444f41

cd examples/hello_world
make TARGET=z1 \
CC="/home/kbessonova/workspace/msp430-clang/build/bin/clang -target msp430" \
AR=/home/kbessonova/ti/msp430-gcc/bin/msp430-elf-ar \
LD=/home/kbessonova/ti/msp430-gcc/bin/msp430-elf-gcc \
CLANG=1
```
Note: all (but ld-related) open PRs were applied.

Compilation was successfull, but linking failed due to #59, that is a stopper o proceed with Contiki:
```
contiki-esb.a(button-sensor.o): In function `irq_p2':
button-sensor.c:(.text+0x4c): undefined reference to `__bic_SR_register_on_exit'
```

**Comment by chbessonova** [comment]
Run Contiki examples on Cooja simulator:
1. Ensure that the repo was cloned with --recursive option.
2. Install Oracle JDK and `ant`
```
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```
Some help, [how to install JDK](https://askubuntu.com/questions/56104/how-can-i-install-sun-oracles-proprietary-java-jdk-6-7-8-or-jre)
3. Workaround [the following issue ](https://github.com/contiki-os/contiki/issues/2214)
4. Run `ant run` and read nice doc [how to create a simulation](https://www.researchgate.net/publication/327238441_Running_and_Testing_Applications_for_Contiki_OS_Using_Cooja_Simulator).

The following list of examples should start and work fine:

- examples/rime 	    
- examples/powertrace 
- examples/sky 
- examples/sky-ip (partially)
- examples/sky-shell-exec
- examples/cfs-coffee

Other examples do not fit into memory.

`printf` (i.e. output) doesn't work as expected if an example linked against libc from msp430-gcc toolchain.
